### PR TITLE
Adding option for matching from particular offset in subject

### PR DESCRIPTION
**Pull request by Kamil93**
Now we can start matching from particular offset in subject.

### CODE REVIEW

**Comment by neurobin** [comment]
* `setStartOffset` and `getStartOffset` seems to be easier names than `setStartFromOffset` and `getStartFromOffset`
* `setStartOffset()` needs a bit more doc to clarify that when FIND_ALL is set, a global match would not be performed on all positions on the subject, rather it will be performed from the start offset and onwards.
* version strings needs to be updated.

**Comment by Kamil93** [comment]
If FIND_ALL is set, startOffset could be just ignored I guess. Tomorrow I'll put the your corrects.

Would be nice to consider also new param in RegexMatch::match(size_t* finish_offset = NULL)
so when it is not NULL, it (var where pointer points) will contain offset where matching ended (one unit after).

**Comment by neurobin** [comment]
> If FIND_ALL is set, startOffset could be just ignored I guess.

No, actually your code as it is, adds an important feature where a global match can be performed from a certain position. If anyone wants to perform global match on all positions, they would have to use `0` as startoffset (which is default).

I forgot to mention, please do the pull request against the master branch (you don't need to update the version or docs in that case). release branch contains a packaged version of the source, and your commit history may be lost in the release branch.

**Comment by neurobin** [comment]
> RegexMatch::match(size_t* finish_offset = NULL)

If you do implement it, please name it `end_offset`

**Pull request closed without merging**
