### PR TITLE
src/jpcre2.hpp: fix getNumberedSubstrings when captures are not matched

### PR DESCRIPTION
**Pull request by rrthomas**
getNumberedSubstrings should leave unmatched captures null

If a capture does not match, it should not be filled in with an empty
string, that’s not the same thing!

Update test_issue_29.cpp to test that captures are filled in if and only if
they are expected from the input data.

Also some cosmetic fixes: fix the spelling of “existing” in an error message, and remove part of a comment that simply repeats the same comment twice on one line.

### CODE REVIEW

**Comment by neurobin** [comment]
Your commit conflicts with issue #29 and unfixes the fix.

**Comment by rrthomas** [comment]
Thanks for the feedback, @neurobin! I have made the simplest fix I can think of: since it is not possible to have null elements in a `std::vec`, I used `std::optional`. Of course, that requires C++17, so I added machinery similar to that for C++11, and made it optional; without C++17, the code stays as it is.

With optional members, `NumSub` is always the right length *and* enables the caller to distinguish matched from unmatched captures.

**Comment by neurobin** [comment]
It changes how the vector elements are accessed by default for c++17 which is not what I would expect. It should be an option like `JPCRE2_USE_STD_OPTIONAL_VECTOR_ELEMENT` or `JPCRE2_UNSET_CAPTURES_NULL` and in the documentation for this macro, it should be mentioned that it requires c++17.

**Comment by neurobin** [comment]
Also, the existing test programs should not be changed. You may write another test (e.g `test_pull_31.cpp`) for this addition.

**Comment by rrthomas** [comment]
Thanks for the feedback, which I'll implement. It's a shame there's no way to rescue the current broken design, but I guess that's the way it is!

**Comment by rrthomas** [comment]
Oooh, I found a bug! A subpattern that starts at position 0 is not returned.

**Comment by rrthomas** [comment]
Oh, I found another bug: the subpattern matches are not overwritten from one call to another, and since PCRE2 doesn't touch elements that don't match, you get back old match data.

**Comment by rrthomas** [comment]
> Also, the existing test programs should not be changed. You may write another test (e.g `test_pull_31.cpp`).

I have updated the PR, but I could not work out how to leave this test program unchanged, since with the new `JPCRE2_UNSET_CAPTURES_NULL` option the behaviour of the library changes, so this test would fail. Can you help?

**Comment by neurobin** [comment]
> with the new JPCRE2_UNSET_CAPTURES_NULL option the behaviour of the library changes, so this test would fail. Can you help?

It won't change the default behavior as you will need to define `JPCRE2_UNSET_CAPTURES_NULL` to use the new feature. Leaving the test programs unchanged will work just fine. In your `test_issue_31.cpp` you will define this macro and write the tests for this addition.

**Comment by rrthomas** [comment]
OK, I just changed `test_issue_29.cpp` to `#undef JPCRE2_UNSET_CAPTURES_NULL`, so the user can set this in `CPPFLAGS` and run the rest of the tests with it active.

`test_pr_31.cpp` is just a copy of `test_issue_29.cpp` that *requires* `JPCRE2_UNSET_CAPTURES_NULL` to be set, so it `#define`s it, testing for C++17 support first, and stubbing out the test if C++17 is not used.

**Comment by neurobin** [comment]
> #undef JPCRE2_UNSET_CAPTURES_NULL

It should not require `#undef`. This should be the default. The previous tests should pass without any modifications at all. You must not change any previous test programs. If the test programs are not returned to their original state, I can not accept this pull request.

**Comment by neurobin** [comment]
> so the user can set this in CPPFLAGS and run the rest of the tests with it active

No need for this.

**Comment by rrthomas** [comment]
> No need for this.

I don't understand this: the user will want to run the tests with the same configuration they are going to use. They can already do this for C++11/17 support, and for other option macros, so why not for this one?

**Comment by neurobin** [comment]
> the user will want to run the tests with the same configuration they are going to use

I will need to review your changes again with a bit more attention. It may take some time.

**Comment by rrthomas** [comment]
@neurobin Many thanks; of course, take your time!

**Review by neurobin — APPROVED** [review]

**Comment by rrthomas** [comment]
Thanks, @neurobin!

**Comment by neurobin** [comment]
> Also, fix a bug where captures that matched at position 0 were not returned.

Do you have the test data/program for this?

**Comment by rrthomas** [comment]
> Do you have the test data/program for this?

No, sorry, I will see if I can make a test in the next few days.

**Comment by rrthomas** [comment]
I have looked into this now, and I cannot see that there was such a bug.

Perhaps I had a bug in my code for PR #31 which I then fixed, and incorrectly wrote the commit message as if the bug existed before my PR?

In any case, I have studied the diff for PR #31, and I have written a test to match a capture at position 0, and run it with the current code and the code from commit 0683463, and it works both times.

I also found and fixed a problem in another test that I introduced in PR #31, for which I will file a PR shortly.

**Comment by neurobin** [comment]
I may or may not make any release with this new macro, because I have come up with a new feature that will solve this problem without adding any compatibility issue.

I intend to provide a MatchResult container that can store the substrings and they can be accessed by both name and number. And the access will be the same as before (e.g `match_res[m][n]`, `match_res[m]["name"]` etc..). In addition to this, you can check if a sub match exists with `if(match_res[m].sub_match(n))` (`"name"` can also be used instead of `n`).

`match_res[m].sub_match(n)` is a SubMatch object. The MatchResult structure is like this:

```
MatchResult
    -> vector<Match>
        -> vector<SubMatch>
```

You can see the `temp` branch where I have put a rough code. Please don't mind the silly mistakes :smile:  , I haven't been coding in c++ for a long time.

**Comment by rrthomas** [comment]
That's fine, for my part I am not using jpcre2 directly, only via the Node binding [pcre2](https://github.com/Kamil93/pcre2), so I don't mind so much what the API is! It does sound better to have a backwards-compatible API, though, and access to matches by name is neat.

**Pull request merged**
