### PR TITLE
Add .gitignore - remove files that shouldn't be in git

### PR DESCRIPTION
**Pull request by floam**
Sorry, my first patch was based on an out of date clone.

Still, the  repository actually takes longer to git clone than many projects 20 years old!

Autotools will populate these m4 files at build time, the files in `m4/` should not be hosted.

```console
floam@rMBP~/s/jpcre2> autoreconf -i -v
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
mkautoreconf: running: /opt/local/bin/aclocal -I m4
daclocal: warning: couldn't open directory 'm4': No such file or directory
iautoreconf: configure.ac: tracing
autoreconf: running: /opt/local/bin/glibtoolize --copy
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /opt/local/bin/autoconf
autoreconf: configure.ac: not using Autoheader
autoreconf: running: /opt/local/bin/automake --add-missing --copy --no-force
autoreconf: Leaving directory `.'
```

### CODE REVIEW

**Comment by neurobin** [comment]
The `ax_cxx_compile_stdcxx.m4` file is required for autoreconf.

> Sorry, my first patch was based on an out of date clone.

So, your patch is obsolete then? it failed all automatic checks though.

And, if you do another pull request, please use the master branch. The release branch actually meant to contain the refined package. But I just push the same thing there for convenience.. I think I will push the packaged content there next time.

**Comment by floam** [comment]
A number of the changes still would apply to master. I'll close this though.

**Comment by neurobin** [comment]
Master branch will contain all the files that is used for development (many of them are not to be used by users). I will make the release branch refined only. It will contain no extra files/directory.

**Comment by floam** [comment]
Hmm, ok. Downside is your history is so heavy, release still takes many minutes to get a checkout. If a project ever includes your code it's unlikely they would import the history and fork properly - just at the size it is now. 

Aaron Gyes

On Thu, Sep 15, 2016 at 12:12 AM Md Jahidul Hamid

<
mailto:Md Jahidul Hamid <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Master branch will contain all the files that is used for development (many of them are not to be used by users). I will make the release branch refined only. It will contain no extra files/directory.

—

You are receiving this because you modified the open/close state.

Reply to this email directly,
https://github.com/jpcre2/jpcre2/pull/5#issuecomment-247253593
, or

**Comment by neurobin** [comment]
> Downside is your history is so heavy ...

Do you have any suggestions on this regard..?

**Comment by neurobin** [comment]
I have cleaned a lot. The total size is around 30MB now, and git clone against the release branch is around 2.3MB

```sh
git clone --depth=1 --branch=release https://github.com/jpcre2/jpcre2
```

**Comment by floam** [comment]
> Do you have any suggestions on this regard..?

Hmm, As you found, aside from a shallow checkout, it's hard to do.

You could keep two seperate repos - you keep these two branches now - the distributed nature of git makes this not actually really easy and you could lose nothing. You could have jpcre2/jpcre2 which has only the "release"-type things pulled in, but on your own non-organization repo (neuorbin/jpcre2), do things a little differently. By squash merging in what you want from neurobin/jpcre2:master to jpcre2/jpcre2:master you might find that fits the current distinction you make between release and master on this repo. The result would be almost equivalent to a shallow checkout but without the drawbacks.

You'd probably want to fork/clone the current repo on the organization to the other spot, then recreate the one here in place with a force push after making a clean version locally.

**Comment by neurobin** [comment]
I think the problem was the PNG files with older versions. There were a lot of them in the HTML document. In current version I didn't keep the HTML document and included a link to the doc in the readme file.

After deleting the previous branches, currently the .git directory is less than a MB. I will re-upload the 10.26 branch without the docs.

**Comment by neurobin** [comment]
This is the current state:

```sh
$ git clone https://github.com/jpcre2/jpcre2
Cloning into 'jpcre2'...
remote: Counting objects: 217, done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 217 (delta 99), reused 3 (delta 3), pack-reused 35
Receiving objects: 100% (217/217), 691.36 KiB | 42.00 KiB/s, done.
Resolving deltas: 100% (103/103), done.
Checking connectivity... done.
```
691KB only!!!

Thanks for all your suggestions. Finally I got it to be satisfying...:D

**Comment by floam** [comment]
Wow, big change.

**Pull request closed without merging**
