### PR TITLE
Adding start_offset, end_offset

### PR DESCRIPTION
**Pull request by Kamil93**
Adding start_offset, end_offset along with API methods and comments.

### CODE REVIEW

**Comment by neurobin** [comment]
```cpp
return getMatchObject().setStartOffset(0).setSubject(s).setModifier(mod).match(); 
```
was wrong, the intention behind using getMatchObject() is to retain the previously set options i.e previously set offset should retain too.

**Comment by Kamil93** [comment]
and it is still about same intention getMatchObject() isn't changed. Only match shortcut method.
Imagine where someone use getMatchObject() to do complex matching and after it somewhere in his code he uses same regex but with shortcut method: regex.match(subject); (with start_offset lets say about at the end) bang, error. regex.match should match sth, but no match returned.

I am thinking about it in context of JavaScript regex.test() function shortcut.

**Comment by neurobin** [comment]
Good point. In that sense, `getMatchObject()` with the shortcut method is error prone too.

**Comment by Kamil93** [comment]
Guess match shortcuts needs seperate MatchRegex object.

**Comment by neurobin** [comment]
Then there will be another problem. Say some one set some vectors without doing the match, then he called the shortcut method to perform the match. Now, he will wonder why the vectors are empty...

It's a tricky decision to make..

**Comment by Kamil93** [comment]
Idea that MatchRegex object from inside JPCRE2 - is for user/client algorithms I think is a bad idea.

**Comment by neurobin** [comment]
It is actually available:

```cpp
RegexMatch& matcher = regex.getMatchObject();
```

**Comment by Kamil93** [comment]
Yes but it created lib-depended object. I mean you can't have more than one at once.

**Comment by neurobin** [comment]
> JPCRE2 could hold one Matcher/MatchRegex obj

That would trigger a huge problem. implementing a deep copy constructor for the RegexMatch would be very bad for performance..

**Comment by Kamil93** [comment]
I mean the Java's Pattern/Matcher idea.

You have a Regex object and you can instantiate as much as you would like to have Matcher out of it.
Plus one additional Matcher inside Regex for shortcut matching methods.

**Comment by neurobin** [comment]
Unlike Java, we need to do the memory management ourselves. If `createMatcher();` creates a new matcher, then it will need to be deleted too and leaving that to the user is a bad thing.

**Comment by neurobin** [comment]
Anyway, I have created some overloads of the shortcut match function to include start_offset as an optional argument. So when writing code, the content assist should show the start_offset entry and the user would most likely notice it. This should solve the unintended mistake. Also I have put some warning on using this shortcut method in the doc.

**Comment by neurobin** [comment]
I think I will make the RegexMatch and RegexReplace object public and thus allow creating arbitrary number of matcher or replacer.

**Comment by neurobin** [comment]
Ok, Now both match function will work the same way i.e there is no room for confusion anymore. Any previously set options will retain its' value unless overridden.

Having multiple match object is available now as a public constructor is made available for both RegexMatch and RegexReplace. Copy constructors are disallowed, because it needs deep copy and they are not important enough to go through the trouble.

Regex class has a copy constructor that performs a deep copy, but use of that copy constructor is discouraged as it spends some extra time copying compiled pattern and JIT memory. Copy ctor will never be needed as getters and setters are enough for all valid purposes.

**Pull request merged**
